export const SAVESHOWDATA = 'SAVESHOWDATA';
export const SAVENEWSDETAILS = 'SAVENEWSDETAILS';
export const CHANGELOADING = 'CHANGELOADING';
export const CHANGESHOWCOMMON = 'CHANGESHOWCOMMON';
export const CHANGETAB = 'CHANGETAB';
