export const SAVESHOWDATA = 'SAVESHOWDATA';
export const PUSHSHOWDATA = 'PUSHSHOWDATA';
export const CHANGESCROLLLOADING = 'CHANGESCROLLLOADING';
export const SAVENEWSDETAILS = 'SAVENEWSDETAILS';
export const CHANGELOADING = 'CHANGELOADING';
export const CHANGESHOWCOMMON = 'CHANGESHOWCOMMON';
export const CHANGETAB = 'CHANGETAB';
export const ISTOEND = 'ISTOEND';
